modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="dmadditions"
version="1.2.2"
displayName="Dalek Mod Additions"
displayURL="https://modrinth.com/mod/dalek-mod-additions"
logoFile="logo.png"
credits="1JamesLeDolphin, SamTiz, Torchwood_one, TheMajorNoob_239"
authors="QRT Studios"
description='''Adds various things, and changes different features of The Dalek Mod'''

updateJSONURL = "https://api.modrinth.com/updates/6XJWjUK9/forge_updates.json"

[[dependencies.dmadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dmadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dmadditions]]
modId="dalekmod"
mandatory=true
versionRange="[65.1.1, )"
ordering="NONE"
side="BOTH"

